default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: unify_user
  password: <%= ENV["UNIFY_DB_USERNAME"] %>

development:
  <<: *default
  database: unify_development

test:
  <<: *default
  database: unify_test

production:
  <<: *default
  database: unify
