default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: h20_user
  password: <%= ENV["HI_DB_PASSWORD"] %>

development:
  <<: *default
  database: h20_development

test:
  <<: *default
  database: h20_test

production:
  <<: *default
  database: h20
